### ISSUE TITLE
Pedsim costmap not updating fast enough and agent always crash with robot

### ISSUE THREAD

**Issue by NamTruongTran0** [Adlink-ROS/neuronbot2#31]
Hey,

thank you for your awesome work and for your outstanding contribution. Your repository has not only accelerated my project but has also enriched my understanding of the subject matter.
I posting the issue here because in you pedsim_ros2 repository there is no issue section :)

Do you know which parameter should i change (in neuronbot_params.yaml) to update the costmap more quickly? 

Thank you so much in advance for you time  ;)

**Comment by QQting** [comment]
Hi @Namo98 

It's been a long time to use pedsim_ros2.
Can you give me the repository including you configurations and show me the instructions how to reproduce the issues?
Thank you.

**Comment by Namo98** [comment]
Thank you so much for your reply i really appreciate your time :)

Actually i cloned you pedsim_ros workspace. It's the turtlebot house environment. I Just added some more agents. Instead of the neuronbot2 i use turtleboot waffle. It look like if i use neuronbot2 it navigates much better but still can't avoid the agents completly. 

Here is the source folder. You can download it and do colcon build:
https://drive.google.com/file/d/1GV166hL8PvpmTfvq0f7WwXoGELHBT1EN/view

Commands:
------------------------------------------------------------
Here you can test the robot:

```
ros2 launch pedsim_gazebo_plugin house_demo_launch.py
ros2 launch pedsim_simulator house_demo_crowd_launch.py simulation_factor:=0.5
ros2 launch neuronbot2_nav bringup_launch.py use_sim_time:=true 
rviz2 -d ~/change_to_your_ws/src/pedsim_ros/pedsim_visualizer/rviz/pedsim.rviz
```

------------------------------------------------------------

**Comment by NamTruongTran0** [comment]
Thank you so much for your reply i really appreciate your time :)

Actually i cloned you pedsim_ros workspace. It's the turtlebot house environment. I Just added some more agents. Instead of the neuronbot2 i using turtleboot waffle. It looks like if i use neuronbot2 it navigates much better but still can't avoid the agents completly.

Questions:

What i have to change to navigate without crashing ?


Thank you in advance

**Comment by QQting** [comment]
I think the problem is not the update rate. Some of the costs should be cleared in costmap after the agent move away.
Why the costmap has not been clear? That's the main issue.

I notice that you have kept your own nav2 stack, may I know why? Is it possible the nav2_costmap_2d is buggy in your nav2 stack?

**Comment by NamTruongTran** [comment]
Thank you for your fast answer.
I got it fixed with the costmap.Not clean as I want it to be but still ok. 
The agents still crash with the robot (see the videos from my last post). If the agent reach close to the robot, the robot don't have enough time to plan a new path
.
Do you know how I can fix this?
I already tried to increase the inflation layer that the robot recognise the agent earlier but it don't work.

I cloned the navigation stack but don't change anything. This should not effect the navigation ^^

Thank you :)

**Comment by NamTruongTran0** [comment]
Often there is a scenario where the robot have to know the dynamic obstacle(agent) in advance in order to avoid a crash.
Do you know how i can achieve this?

Mayber create a bigger shape in front of the agent that the robot knows in advance that the agent will arrive?
![Screenshot from 2023-08-19 15-33-17](https://github.com/Adlink-ROS/neuronbot2/assets/137286127/e74d0a22-d2a8-458c-ba5f-5b438384e8e7)

Do you know how to create such a shape for the layer?

**Comment by QQting** [comment]
In ROS1, there is a package called social navigation layers, please refer to this link https://wiki.ros.org/social_navigation_layers?distro=melodic


> https://streamable.com/g3hfuk

In this video, the costmap is still not been cleared, please fix it. Maybe try to adjust the resolution of the simulated lidar.

**Comment by Namo98** [comment]
> In ROS1, there is a package called social navigation layers, please refer to this link https://wiki.ros.org/social_navigation_layers?distro=melodic
> 
> > https://streamable.com/g3hfuk
> 
> In this video, the costmap is still not been cleared, please fix it. Maybe try to adjust the resolution of the simulated lidar.

Thank you so much for your help i really appreciate your time.

In this video i using your params file (neuronbot_params.yaml) but the the costmap is still not cleared well:
https://streamable.com/g3hfuk

Actually i found the repository for the social navigation layer for ros2:
https://github.com/robotics-upo/nav2_social_costmap_plugin

I  implemented the plugin but it still crash. The social layer is not working proper?

Can you test it maybe on your system?
I already created a repository where i fixed the errors.(Distro foxy) 
You just have to clone the repository and change the neuronbot_params.yaml file:
https://github.com/Namo98/ros2_social_navigation_layer

**Comment by QQting** [comment]
Sorry, I'm busy these days. Can't spend too much time on this.

**Comment by NamTruongTran0** [comment]
No problem. I’m very greatful for your replies. 

i know why the layer don’t work. In the beginning I thought it is just plug and play but I have to publish the data of the pedsim agents to the /people topic. So that the Social layer can subscribe to the /people topic and create a layer around the agents. 

Did you already worked with the social navigation layer?

**Comment by QQting** [comment]
> Did you already worked with the social navigation layer?

No, I have no time to check that, sorry.
